name: workflow
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
  workflow_dispatch:
jobs:
  workflow:
    name: Workflow
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install Packages
        run: |
          corepack enable
          pnpm i
      - name: Lint & Submodules
        if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git submodule update --remote --merge
          pnpm lint
          git pull && git commit -am "Fix Lint" && git push || echo "Done"
      - name: Build
        run: pnpm build
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
        with:
          target_branch: gh-pages
          build_dir: .vuepress/dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
